[platformio]
src_dir = main

[env:esp32dev]
platform = espressif32
framework = espidf
board = esp32dev

; Configurações específicas do projeto
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = partitions.csv
board_build.filesystem = spiffs

; Habilitar PSRAM
build_flags =
    -DCONFIG_SPIRAM_SUPPORT=1
    -DCONFIG_SPIRAM_SPEED_80M=1

; Configurações do LVGL
lib_deps =
    lvgl/lvgl @ ^8.3.9

; Configurações de upload
upload_speed = 115200
upload_protocol = esptool
upload_flags =
    --no-stub

; Configurações de debug
debug_tool = esp-prog
debug_init_break = tbreak setup

; Configurações de memória
board_build.f_cpu = 80000000L
board_build.f_flash = 40000000L
board_build.flash_mode = dio
